### ISSUE TITLE
NGINX redirect

### ISSUE THREAD

**Issue by daktak** [web-tech-tw/arona#27]
Information that could be added to the documentation.

You can use nginx to host the webhook in a sub-path like below. This also allows you to change the port number , and or add an ssl cert etc.

config.yaml
```
http:
  bindHost: 127.0.0.1
  bindPort: 3000
  baseUrl: "https://external:443/arona/"
```

nginx.conf
```
location /arona {
        rewrite ^/arona/(.*) /$1 break;
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
}
```

So the setting for line would be
https://external:443/arona/hooks/line
